name: Integrate Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Building Next.js App from Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Production Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - name: Building Next.js App
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: .next/*

  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: build
          path: .next/*
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${GITHUB_REF##*/} .
      - name: Login to GitHub Container Registry (ghcr.io)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Publish Docker Image
        run: docker push ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${GITHUB_REF##*/}

  deploy:
    name: Deploy to Google Cloud Platform
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry (ghcr.io)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Setup Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true
      - name: Pull Docker Image
        run: docker pull ghcr.io/iamfj/${{ github.event.repository.name }}:${GITHUB_REF##*/}
      - name: Relabel Docker Image
        run: docker tag \
          ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${GITHUB_REF##*/} \
          gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}:${GITHUB_REF##*/}
      - name: Configure Docker
        run: gcloud auth configure-docker
      - name: Public Docker Image
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}:${GITHUB_REF##*/}
          gcloud config set run/region us-central1
      - name: Deploy to Google Cloud Platform
        run: |
          gcloud run deploy ${{ secrets.GCP_APPLICATION }} \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}:${GITHUB_REF##*/} \
            --platform managed \
            --allow-unauthenticated \
            --memory 512M
